version: '3'
services:

  frontend:
    build: ./frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "8000:8000"        # ← corrigé : Laravel = 8000
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: todolist
      DB_USERNAME: root
      DB_PASSWORD: root

  db:
    image: mysql:8.0
    container_name: todolist_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todolist
    ports:
      - "3306:3306"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql

  # ← AJOUT phpMyAdmin
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: todolist_phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - db

volumes:
  db_data:

